### ISSUE TITLE
I'm seeking some guidance on using exqlite under termux

### ISSUE THREAD

**Issue by leorodriguesrj** [elixir-sqlite/exqlite#174]
G'day! I'm trying to use exqlite in a project running on [termux](https://github.com/termux/termux-app).

While running `mix deps.compile`, the process fails to load the NIF module because the symbol `trunc` is not found. The following warning message is displayed when I run `mix test` at the root of the exqlite repository after cloning:

```
09:58:01.355 [warn]  The on_load function for module Elixir.Exqlite.Sqlite3NIF returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen failed: cannot locate symbol "trunc" referenced by "/data/data/com.termux/files/home/develop/by-language/elixir/exqlite/_build/test/lib/exqlite/priv/sqlite3_nif.so"...\''}}
```

I'm supposing there is a missing library in my system but I fail to determine what library.

Could you guys offer-me some guidance?

**Comment by warmwaffles** [comment]
@dominicletz maybe you can shed some light on this.

@leorodriguesrj I think you'll need to `export CROSSCOMPILE=Android` in order to get the correct symbols generated https://github.com/elixir-sqlite/exqlite/blob/main/Makefile#L38-L45

**Comment by dominicletz** [comment]
Interesting message on `trunc`. On Android generally, the CFLAG=`-z global` is important because of Androids' different treatment of dlopen scoping. 

But in this case it could also just be a compiler version issue. The `trunc` method is defined in sqlite3 only when it's detected during compilation:

```
#if SQLITE_HAVE_C99_MATH_FUNCS
    MFUNCTION(trunc,             1, trunc,     ceilingFunc ),
#endif
```

I don't know which compiler and standard library termux is using, but maybe there is a problem?

I suggest first a quick check with CFLAGS=`-z global` and if the problem still occurs you might give LDFLAGS=`-lm` a try to see if it `trunc` is coming from the standard math library in termux. Otherwise you have to dig deeper into this termux specifically.

Cheers

**Comment by leorodriguesrj** [comment]
@dominicletz The LDFLAGS solved the the problem. I am now facing a different issue since ExSqlean is compiled to EM_X86_64 instead of EM_AARCH64. At the moment I'm trying to compile ExSqlean with the correct architecture and if I manage to do that, how do I get the new version of ExSqlean to be used by exqlite? Is there a way to trigger it's compilation?

**Comment by warmwaffles** [comment]
@leorodriguesrj `ex_sqlean` is really only for `dev` and `test` not necessary for downstream use. 

```elixir
{:ex_sqlean, "~> 0.8.5", only: [:dev, :test]},
```

@mindreframer might want to chime in here and see if they can support android compilation

**Comment by leorodriguesrj** [comment]
@warmwaffles Great! I have my main project working correctly!

**Comment by warmwaffles** [comment]
@leorodriguesrj good to hear!
